# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  # terraform
  init:
    cmds:
      - terraform init
    dir: infrastructure
  plan:
    cmds:
      - terraform plan
    dir: infrastructure

  apply:
    dir: infrastructure
    cmds:
      - terraform apply -auto-approve

  destroy:
    dir: infrastructure
    cmds:
      - terraform destroy -auto-approve

  outputs:
    dir: infrastructure
    cmds:
      - terraform output

  # build vue js
  build:
    dir: frontend
    cmds:
      - npm run build
